#pragma once

#include <QtOrm/qormglobal.h>

#include <QtCore/qstring.h>
#include <QtCore/qvariant.h>

QT_BEGIN_NAMESPACE

class Q_ORM_EXPORT QOrmPropertyMapping
{
public:
    Q_REQUIRED_RESULT
    QString classPropertyName() const;
    void setClassPropertyName(const QString& propertyName);

    Q_REQUIRED_RESULT
    QString tableFieldName() const;
    void setTableFieldName(const QString& tableFieldName);

    Q_REQUIRED_RESULT
    bool isObjectId() const;
    void setIsObjectId(bool isObjectId);

    Q_REQUIRED_RESULT
    bool isAutogenerated() const;
    void setIsAutogenerated(bool isAutogenerated);

    Q_REQUIRED_RESULT
    QVariant::Type dataType() const;
    void setDataType(QVariant::Type type);

private:
    QString m_classPropertyName;
    QString m_tableFieldName;
    bool m_isObjectId{false};
    bool m_isAutogenerated{false};
    QVariant::Type m_dataType{QVariant::Invalid};
};


QT_END_NAMESPACE
