#include "qormpropertymapping.h"

QT_BEGIN_NAMESPACE

QString QOrmPropertyMapping::classPropertyName() const
{
    return m_classPropertyName;
}

void QOrmPropertyMapping::setClassPropertyName(const QString& classPropertyName)
{
    m_classPropertyName = classPropertyName;
}

QString QOrmPropertyMapping::tableFieldName() const
{
    return m_tableFieldName;
}

void QOrmPropertyMapping::setTableFieldName(const QString& tableFieldName)
{
    m_tableFieldName = tableFieldName;
}

bool QOrmPropertyMapping::isObjectId() const
{
    return m_isObjectId;
}

void QOrmPropertyMapping::setIsObjectId(bool isObjectId)
{
    m_isObjectId = isObjectId;
}

bool QOrmPropertyMapping::isAutogenerated() const
{
    return m_isAutogenerated;
}

void QOrmPropertyMapping::setIsAutogenerated(bool isAutogenerated)
{
    m_isAutogenerated = isAutogenerated;
}

QVariant::Type QOrmPropertyMapping::dataType() const
{
    return m_dataType;
}

void QOrmPropertyMapping::setDataType(QVariant::Type dataType)
{
    m_dataType = dataType;
}

QT_END_NAMESPACE
