#ifndef QORMPROPERTYMAPPING_H
#define QORMPROPERTYMAPPING_H

#include <QtOrm/qormglobal.h>

#include <QtCore/qmetaobject.h>
#include <QtCore/qshareddata.h>
#include <QtCore/qstring.h>
#include <QtCore/qvariant.h>

QT_BEGIN_NAMESPACE

class QOrmMetadata;
class QOrmPropertyMappingPrivate;

class Q_ORM_EXPORT QOrmPropertyMapping
{
public:
    QOrmPropertyMapping(const QOrmMetadata& enclosingEntity,
                        QMetaProperty qMetaProperty,
                        QString classPropertyName,
                        QString tableFieldName,
                        bool isObjectId,
                        bool isAutoGenerated,
                        QVariant::Type dataType,
                        const QOrmMetadata* referencedEntity,
                        bool isTransient);
    QOrmPropertyMapping(const QOrmPropertyMapping&);
    QOrmPropertyMapping(QOrmPropertyMapping&&);
    ~QOrmPropertyMapping();

    QOrmPropertyMapping& operator=(const QOrmPropertyMapping&);
    QOrmPropertyMapping& operator=(QOrmPropertyMapping&&);

    Q_REQUIRED_RESULT
    const QOrmMetadata& enclosingEntity() const;

    Q_REQUIRED_RESULT
    const QMetaProperty& qMetaProperty() const;

    Q_REQUIRED_RESULT
    QString classPropertyName() const;

    Q_REQUIRED_RESULT
    QString tableFieldName() const;

    Q_REQUIRED_RESULT
    bool isObjectId() const;

    Q_REQUIRED_RESULT
    bool isAutogenerated() const;

    Q_REQUIRED_RESULT
    QVariant::Type dataType() const;

    Q_REQUIRED_RESULT
    QString dataTypeName() const;

    Q_REQUIRED_RESULT
    bool isReference() const;

    Q_REQUIRED_RESULT
    const QOrmMetadata* referencedEntity() const;

    Q_REQUIRED_RESULT
    bool isTransient() const;

private:
    QSharedDataPointer<QOrmPropertyMappingPrivate> d;
};

extern Q_ORM_EXPORT QDebug operator<<(QDebug dbg, const QOrmPropertyMapping& propertyMapping);

QT_END_NAMESPACE

#endif
