on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        qtversion: [ '5.12.9', '5.15.1' ]
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v2.9.0
      with: 
        version: ${{ matrix.qtversion }}
        extra: '--archives qt qtbase qtdeclarative qtquickcontrols2 icu'
   
    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build
      
    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=Debug -DQTORM_BUILD_EXAMPLES=ON -DQTORM_BUILD_TESTS=ON -DQTORM_BUILD_SHARED_LIBS=ON
      
    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: cmake --build . --config Debug

    - name: Test
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: ctest -C Debug
