on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: windows-2019
          qtversion: '5.15.1'
          arch: 'win64_msvc2019_64'
        - os: windows-2016 
          qtversion: '5.12.9'
          arch: 'win64_msvc2017_64'
        
    runs-on: ${{ matrix.os }}    
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v2.9.0
      with: 
        version: ${{ matrix.qtversion }}
        extra: '--archives qt qtbase qtdeclarative qtquickcontrols2 icu'
   
    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build
      
    - name: Configure CMake
      working-directory: ${{runner.workspace}}/build      
      run: cmake ${env:GITHUB_WORKSPACE} -A x64 -DQTORM_BUILD_EXAMPLES=ON -DQTORM_BUILD_TESTS=ON -DQTORM_BUILD_SHARED_LIBS=ON
      
    - name: Build
      working-directory: ${{runner.workspace}}/build
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: cmake --build . --config Debug

    - name: Test
      working-directory: ${{runner.workspace}}/build            
      run: |
        ${env:Path} = "${{runner.workspace}}/build/src/Debug;${env:Path}"
        ctest -C Debug
