on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
        - qtversion: '5.15.*'
          arch: 'win64_msvc2019_64'
        - qtversion: '5.12.*'
          arch: 'win64_msvc2017_64'
        - qtversion: '6.8.*'
          arch: 'win64_msvc2022_64'
        
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with: 
        version: ${{ matrix.qtversion }}
        arch: ${{ matrix.arch }}
        archives: 'qtbase qtdeclarative qtquickcontrols2'
   
    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build
      
    - name: Configure CMake
      working-directory: ${{runner.workspace}}/build      
      run: cmake ${env:GITHUB_WORKSPACE} -A x64 -DQTORM_BUILD_EXAMPLES=ON -DQTORM_BUILD_TESTS=ON -DQTORM_BUILD_SHARED_LIBS=ON
      
    - name: Build
      working-directory: ${{runner.workspace}}/build
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: cmake --build . --config Debug

    - name: Test
      working-directory: ${{runner.workspace}}/build            
      run: |
        ${env:Path} = "${{runner.workspace}}/build/src/Debug;${env:Path}"
        ctest -C Debug --output-on-failure
