on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:        
        qtversion: [ '5.15.*' ]
        
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with: 
        version: ${{ matrix.qtversion }}
        archives: 'qtbase qtdeclarative qtquickcontrols2 icu'
   
    - name: Install Qbs
      run: |
        wget --no-check-certificate --content-disposition https://download.qt.io/official_releases/qbs/1.24.1/qbs-linux-x86_64-1.24.1.tar.gz
        tar xzvf qbs-linux-x86_64-1.24.1.tar.gz
        QBS_BIN_DIR="${GITHUB_WORKSPACE}/qbs-linux-x86_64-1.24.1/bin"
        echo "$QBS_BIN_DIR" >> ${GITHUB_PATH}
      shell: bash

    - name: Configure Qbs
      run: |
        qbs-setup-toolchains $(command -v gcc) gcc
        qbs-setup-qt $(command -v qmake) qt5
        qbs-config profiles.qt5.baseProfile gcc
      shell: bash

    - name: Build
      run: qbs build profile:qt5
      shell: bash

    - name: Test
      run: qbs build profile:qt5 -p autotest-runner
      shell: bash
