on: [push, pull_request]

jobs:
  build:    
    strategy:
      fail-fast: false
      matrix:        
        qtversion: [ '5.12.*', '5.15.*' ]
        
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with: 
        version: ${{ matrix.qtversion }}
        archives: 'qtbase qtdeclarative qtquickcontrols2 icu'
   
    - name: Create Build Environment
      shell: bash 
      run: mkdir -p ${{runner.workspace}}/build
      
    - name: Configure QMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: qmake ${GITHUB_WORKSPACE}/qtorm.pro
      
    - name: Build
      working-directory: ${{runner.workspace}}/build
      shell: bash     
      run: make

    - name: Test
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: make check
